import type { ConfigContext, ConfigFile } from '../config-generator'
import type { PersonaId } from '../persona-registry'

/**
 * Generate Fan Control XML configuration
 * Links case fans to GPU temperature for optimal cooling
 */
export function generateFanControlConfig(context: ConfigContext): ConfigFile[] {
  const { persona, hardware } = context
  const gpuVendor = hardware.gpu

  // Fan curve points: [temp, fanSpeed]
  // Same curves as Afterburner for consistency
  const fanCurves: Record<PersonaId, number[][]> = {
    gamer: [
      [30, 30],
      [40, 35],
      [50, 45],
      [60, 60],
      [70, 80],
      [80, 100],
    ],
    pro_gamer: [
      [30, 35],
      [40, 45],
      [50, 60],
      [60, 75],
      [70, 90],
      [75, 100],
    ],
    benchmarker: [
      [30, 50],
      [40, 65],
      [50, 80],
      [60, 95],
      [70, 100],
    ],
    streamer: [
      [30, 30],
      [40, 40],
      [50, 50],
      [60, 65],
      [70, 85],
      [80, 100],
    ],
  }

  const curve = fanCurves[persona]
  const gpuName = gpuVendor.toUpperCase()

  const config = generateFanControlXML(curve, gpuName, persona)
  const filename = `rocktune-fancontrol-${persona}-${gpuVendor}.xml`

  const instructions = `FAN CONTROL IMPORT INSTRUCTIONS

1. BACKUP FIRST:
   - Open Fan Control app
   - Click "Export" button (💾 icon)
   - Save your current configuration

2. IMPORT CONFIG:
   - Click "Import" button (📂 icon)
   - Select: ${filename}
   - Click "OK" to apply

3. VERIFY SENSORS:
   - Check that GPU temperature sensor is detected
   - Ensure case fan headers are recognized
   - Test fan speed response by stressing GPU

4. ENABLE AUTO-START:
   - Settings → "Start with Windows"
   - Settings → "Start minimized"
   - Fan curve will activate automatically

PERSONA: ${persona.replace(/_/g, ' ').toUpperCase()}
GPU: ${gpuName}

STRATEGY:
${getPersonaStrategy(persona)}

KEY FEATURES:
- Case fans follow GPU temp (not just CPU)
- 3°C hysteresis prevents fan ramping
- Smooth curve transitions
- Auto-start with Windows

SAFETY NOTES:
- Monitor temps during first gaming session
- Adjust curve if fans are too loud/quiet
- ${gpuVendor === 'amd' ? 'AMD GPUs run hotter - this is normal' : 'NVIDIA GPUs throttle at 83°C'}
- Ensure case has adequate intake/exhaust`

  return [
    {
      filename,
      content: config,
      format: 'xml',
      instructions,
    },
  ]
}

function generateFanControlXML(
  curve: readonly (readonly number[])[],
  gpuName: string,
  persona: string,
): string {
  // Fan Control XML format
  const curvePoints = curve
    .map(
      ([temp, speed]) =>
        `    <Point><Temperature>${temp}</Temperature><Speed>${speed}</Speed></Point>`,
    )
    .join('\n')

  return `<?xml version="1.0" encoding="utf-8"?>
<FanControlConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>RockTune_${persona}_${gpuName}</Name>
  <Description>Generated by RockTune - https://rocktune.pedroferrari.com</Description>

  <!-- Fan Curve: ${getPersonaStrategy(persona)} -->
  <FanCurve>
    <Name>GPU Temperature → Case Fans</Name>
    <TemperatureSource>MaxOfCPUAndGPU</TemperatureSource>
    <Hysteresis>3</Hysteresis>
    <Points>
${curvePoints}
    </Points>
  </FanCurve>

  <Settings>
    <StartMinimized>true</StartMinimized>
    <MinimizeToTray>true</MinimizeToTray>
    <MinimizeOnClose>true</MinimizeOnClose>
    <StartWithWindows>true</StartWithWindows>
  </Settings>
</FanControlConfig>`
}

function getPersonaStrategy(persona: string): string {
  switch (persona) {
    case 'gamer':
      return 'Balanced cooling - moderate noise, good temps'
    case 'pro_gamer':
      return 'Aggressive cooling - higher noise, best temps'
    case 'benchmarker':
      return 'Maximum cooling - high noise, lowest temps'
    case 'streamer':
      return 'Quiet operation - lower noise, acceptable temps'
    default:
      return 'Custom cooling curve'
  }
}
