import type { ConfigContext, ConfigFile } from "../config-generator";

/**
 * Generate OBS Studio configuration files
 * Returns multiple files: global.ini (settings) and basic.ini (profile)
 */
export function generateOBSConfigs(context: ConfigContext): ConfigFile[] {
  const { persona, hardware } = context;
  const gpuVendor = hardware.gpu;

  // Encoder selection based on GPU
  const encoder = getEncoder(gpuVendor);
  const encoderPreset = getEncoderPreset(gpuVendor, persona);

  const globalIni = generateGlobalIni(encoder, encoderPreset, gpuVendor);
  const basicIni = generateBasicIni(persona);

  const instructions = `OBS STUDIO CONFIG IMPORT INSTRUCTIONS

1. BACKUP FIRST:
   - Close OBS if it's running
   - Navigate to: %APPDATA%\\obs-studio\\
   - Copy the entire folder as backup

2. IMPORT CONFIGS:
   - Extract both files to: %APPDATA%\\obs-studio\\basic\\profiles\\RockTune\\
   - Create the "RockTune" folder if it doesn't exist
   - Place global.ini and basic.ini in this folder

3. SELECT PROFILE:
   - Open OBS Studio
   - Go to Profile menu → RockTune
   - OBS will restart with new settings

4. VERIFY SETTINGS:
   - Settings → Output → Streaming
   - Encoder: ${encoder}
   - Bitrate: 6000 Kbps (Twitch max)
   - Preset: ${encoderPreset}
   - Settings → Video
   - Output Resolution: 1920x1080
   - FPS: 60

PERSONA: ${persona.toUpperCase()}
GPU: ${gpuVendor.toUpperCase()}
ENCODER: ${encoder}

ENCODING STRATEGY:
${getEncoderStrategy(gpuVendor, persona)}

KEY FEATURES:
- Hardware-accelerated encoding (${encoder})
- Optimized for ${
    persona === "streamer" ? "streaming quality" : "balanced performance"
  }
- Twitch-compliant bitrate (6000 Kbps)
- 1080p60 output
- Keyframe interval: 2s (required by Twitch)

NEXT STEPS:
- Set up scenes and sources
- Add game capture source
- Test stream with "Start Recording" first
- Check CPU/GPU usage during test
- Adjust bitrate if you have < 10 Mbps upload speed`;

  return [
    {
      filename: `rocktune-obs-global-${persona}-${gpuVendor}.ini`,
      content: globalIni,
      format: "ini",
      instructions,
    },
    {
      filename: `rocktune-obs-basic-${persona}-${gpuVendor}.ini`,
      content: basicIni,
      format: "ini",
      instructions,
    },
  ];
}

function getEncoder(gpuVendor: string): string {
  switch (gpuVendor) {
    case "nvidia":
      return "jim_nvenc"; // NVIDIA NVENC
    case "amd":
      return "amd_amf_h264"; // AMD AMF
    case "intel":
      return "obs_qsv11"; // Intel QuickSync
    default:
      return "x264"; // Software fallback
  }
}

function getEncoderPreset(gpuVendor: string, persona: string): string {
  if (gpuVendor === "nvidia") {
    // NVENC presets
    return persona === "streamer" ? "quality" : "performance";
  }
  if (gpuVendor === "amd") {
    // AMF presets
    return persona === "streamer" ? "quality" : "balanced";
  }
  // x264/QuickSync
  return persona === "streamer" ? "medium" : "veryfast";
}

function getEncoderStrategy(gpuVendor: string, persona: string): string {
  const encoderName = {
    nvidia: "NVIDIA NVENC",
    amd: "AMD AMF",
    intel: "Intel QuickSync",
  }[gpuVendor] || "Software (x264)";

  const strategy = persona === "streamer"
    ? "Quality-focused - better visual quality, slightly more GPU usage"
    : "Performance-focused - lower GPU overhead, still good quality";

  return `Using ${encoderName}\n${strategy}`;
}

function generateGlobalIni(
  encoder: string,
  preset: string,
  gpuVendor: string,
): string {
  return `[General]
Name=RockTune

[Video]
BaseCX=1920
BaseCY=1080
OutputCX=1920
OutputCY=1080
FPSCommon=60

[Output]
Mode=Simple

[SimpleOutput]
VBitrate=6000
StreamEncoder=${encoder}
ABitrate=160
RecQuality=Stream
RecEncoder=${encoder}

[AdvOut]
Encoder=${encoder}
RecEncoder=${encoder}

[${encoder}]
preset=${preset}
rate_control=CBR
bitrate=6000
keyint_sec=2
bf=2
${gpuVendor === "nvidia" ? "profile=high\nlevel=auto\nlookahead=0" : ""}
${gpuVendor === "amd" ? "Usage=ultralowlatency\nProfile=high" : ""}

; Generated by RockTune - https://rocktune.pedroferrari.com
; Optimized for ${gpuVendor.toUpperCase()} GPU
; Preset: ${preset}`;
}

function generateBasicIni(persona: string): string {
  return `[General]
Name=RockTune_${persona}

[Video]
BaseCX=1920
BaseCY=1080
OutputCX=1920
OutputCY=1080
FPSType=0
FPSCommon=60/1

[Audio]
SampleRate=48000
Channels=Stereo

; Generated by RockTune - https://rocktune.pedroferrari.com
; Persona: ${persona}`;
}
